name: drift-dagger
channels:
  - nvidia
  - conda-forge
dependencies:
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-toolkit=12.1.0
  - numba=0.59.1
  - numpy=1.26.4
  - scipy=1.13.0
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - pillow=9.4.0
  - python=3.11.6
  - pyyaml=6.0.1
  - imageio=2.34.1
  - libstdcxx-ng=13.2.0
  - pip=24.0
  - pip:
      - diffusers==0.30.3
      - einops==0.8.0
      - gymnasium==1.0.0a2
      - hydra-core==1.3.2
      - mujoco==3.1.5
      - moviepy==1.0.3
      - nlopt==2.7.1
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - opencv-contrib-python==4.9.0.80
      - pygame==2.5.2
      - pyrealsense2==2.54.2.5684
      - tensorboard==2.16.2
      - tensorboard-plugin-wit==1.8.1
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - zarr==2.18.1
      - -e ./mavis_mujoco
      - ./mavis_mujoco/xArm-Python-SDK
